[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_blink = "97otWVsih7AnELD1BsZsrzgmNq1PkqGFp2iJbG2XapYd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kenyor/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
